<?php
/* 
 * config.php
 * -Lee Hall Thu 06 Sep 2012 10:10:03 PM EDT
 *
 * This file opens the database connection and provides some useful global
 * variables to the project
 */

$conn_str="user=apache dbname=honeycomb";
$conn= pg_connect($conn_str);
if (!$conn) 
    die("Unable to connect to database.");

function db_cleanup($conn){
    pg_close($conn);
}
register_shutdown_function('db_cleanup', $conn);

$URL_BASE="https://$_SERVER[SERVER_NAME]";
$FILE_STORE="/var/www/honeycomb/file_store";
$FILE_URL=$URL_BASE . "/file_store";

// Set the default timezone for calls to date().
// Everythign generated by PHP should go in the DB, and it can be queried in
// the proper TZ at that point.
date_default_timezone_set('UTC');
?>
